<?php
$url = array(
"https://i.imgur.com/GWSfqIL.jpg",
"https://i.imgur.com/RtNV4Lh.jpg",
"https://i.imgur.com/u19QQjV.jpg",
"https://i.imgur.com/exoolPy.jpg",
"https://i.imgur.com/GdSVBAr.jpg",
"https://i.imgur.com/g11OFVv.jpg",
"https://i.imgur.com/gouxA4p.jpg",
"https://i.imgur.com/4Tw6g2U.jpg",
"https://i.imgur.com/8MTwfb7.jpg",
"https://i.imgur.com/iRzK33A.jpg",
"https://i.imgur.com/sEQgWJZ.jpg",
"https://i.imgur.com/ApmK12d.jpg",
"https://i.imgur.com/p74z5Ha.jpg",
"https://i.imgur.com/i6a3kL1.jpg",
"https://i.imgur.com/Pt0AeYr.jpg",
"https://i.imgur.com/GWSfqIL.jpg",
"https://i.imgur.com/VAk4Sy0.jpg",
"https://i.imgur.com/C7KcTQv.jpg",
"https://i.imgur.com/rWtox5Z.jpg",
"https://i.imgur.com/z8MOL00.jpg",
"https://i.imgur.com/US71tYn.jpg",
"https://i.imgur.com/NNVdvLb.jpg",
"https://i.imgur.com/GWSfqI.jpg",
"https://i.imgur.com/4Aqa9hN.jpg",
"https://i.imgur.com/TIHmT2B.jpg",
"https://i.imgur.com/yIamHiD.jpg",
"https://i.imgur.com/IjhHFKL.jpg",
"https://i.imgur.com/wtWWx7d.jpg",
"https://i.imgur.com/9Yhmo9C.jpg",
"https://i.imgur.com/VAk4Sy0.jpg",
"https://i.imgur.com/sSHT8gi.jpg",
"https://i.imgur.com/DxGTmws.jpg",
"https://i.imgur.com/tnX4ADc.jpg",
"https://i.imgur.com/qd3QhoA.jpg",
"https://i.imgur.com/Id2Slnk.jpg",
"https://i.imgur.com/Br7LXN8.jpg",
"https://i.imgur.com/ax37AsF.jpg",
"https://i.imgur.com/24euyiI.jpg",
"https://i.imgur.com/lrMOwOi.jpg",
"https://i.imgur.com/4QrvAfW.jpg",
"https://i.imgur.com/0EgzvyV.jpg",
"https://i.imgur.com/ByFeG9X.jpg",
"https://i.imgur.com/aL25hqK.jpg",
"https://i.imgur.com/oEgrusw.jpg",
"https://i.imgur.com/VqlckqE.jpg",
"https://i.imgur.com/626zX3H.jpg",
"https://i.imgur.com/yYmUNdq.jpg",
"https://i.imgur.com/C7KcTQv.jpg",
"https://i.imgur.com/8MTwfb7.jpg",
"https://i.imgur.com/evRhADX.jpg",
"https://i.imgur.com/dtWDruL.jpg",
"https://i.imgur.com/GPTDvra.jpg",
"https://i.imgur.com/pIoLLRW.jpg",
"https://i.imgur.com/FBUAbnA.jpg",
"https://i.imgur.com/dCQ6rA4.jpg",
"https://i.imgur.com/CL6WxkY.jpg",
"https://i.imgur.com/oFohrSZ.jpg",
"https://i.imgur.com/VqlckqE.jpg",
"https://i.imgur.com/njSomiL.jpg",
"https://i.imgur.com/jAbCtX2.jpg",
"https://i.imgur.com/F4ySFP2.jpg",
"https://i.imgur.com/9w2trPu.jpg",
"https://i.imgur.com/ExVdeyf.jpg",
"https://i.imgur.com/iO7A4Cc.jpg",
"https://i.imgur.com/Unn9Mib.jpg",
"https://i.imgur.com/z8MOL00.jpg",
"https://i.imgur.com/dCQ6rA4.jpg",
"https://i.imgur.com/Qd4u2OE.jpg",
"https://i.imgur.com/ax37AsF.jpg",
"https://i.imgur.com/rqhcost.jpg",
"https://i.imgur.com/cArQg5v.jpg",
"https://i.imgur.com/DxGTmws.jpg",
"https://i.imgur.com/4ECI9LU.jpg",
"https://i.imgur.com/HWwSXug.jpg",
"https://i.imgur.com/IxzLyvP.jpg",
"https://i.imgur.com/fW8YAJn.jpg",
);
$tuandz = array_rand($url);
$tuandeeptry = $url [$tuandz];
$xoa = array(
"url" => $tuandeeptry,
"author" => "VietKhanhApi",
"success" => "true",
);
$rdimg = json_encode($xoa);

$i = ['\/v\/','\/','VietKhanhApi'];
$t = ['/v/','/','VietKhanhApi'];
$j = str_replace($i, $t, $rdimg);
echo $j;
